
services:
 
  db:
    image: postgres:latest
    container_name: db_service_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d   
    
  
  api:
    build:
      context: ./APIs
      dockerfile: Dockerfile
    container_name: api_service
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network
    ports:
      - "8080:8080"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: